import Head from 'next/head'
import Template from '../components/template/Template'
import Loader from '../components/loader/Loader'
import Balance from '../components/balance/Balance'

export default function balance() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template>
            <Balance/>
        </Template>
      </main>
    </div>
  )
}


