import Head from 'next/head'
import Template from '../components/template/Template'
import Community from '../components/communities/Community'

export default function CommunitiesPage() {

    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template>
            <Community rank="1" name="TacoCat" totalPoints="400"/>
            <Community rank="2" name="PotatoDog" totalPoints="383"/>
            <Community rank="3" name="TomatoStew" totalPoints="310"/>
            <Community rank="4" name="RabbitFur" totalPoints="298"/>
            <Community rank="5" name="Stinky Socks" totalPoints="284"/>
            <Community rank="6" name="TomatoStew" totalPoints="310"/>
            <Community rank="7" name="RabbitFur" totalPoints="298"/>
            <Community rank="8" name="Stinky Socks" totalPoints="284"/>
            <section className='communityPadding'></section>
        </Template>
      </main>
    </div>
    )
}
  
  
  