import React from 'react'
import Head from 'next/head'
import Template from '../components/template/Template'
import Communities from '../components/communities/Communities'

export default function CommunitiesHome() {

    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template>
          <Communities/>
        </Template>
      </main>
    </div>
    )
  }
  
  
  