import React, { useState } from 'react';
import Calendar from 'react-calendar';
import Head from 'next/head'
import Template from '../components/template/Template'

export default function CreateGoals() {
  const [value, onChange] = useState(new Date());

    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template>
          <section className='createGoals'>
            <section>
              <div> 
                <h2> Create Goals </h2>
              </div>
              <div>
                <div> 
                  <input type="text" id="name" name="name" required
                  minlength="4" maxlength="8" size="10" placeholder='Enter Email'></input>  
                  <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M20.822 18.096c-3.439-.794-6.64-1.49-5.09-4.418 4.72-8.912 1.251-13.678-3.732-13.678-5.082 0-8.464 4.949-3.732 13.678 1.597 2.945-1.725 3.641-5.09 4.418-3.073.71-3.188 2.236-3.178 4.904l.004 1h23.99l.004-.969c.012-2.688-.092-4.222-3.176-4.935z"/></svg>
                  </div>
                </div>

                <div> 
                  <input type="text" id="name" name="name" required
                  minlength="4" maxlength="8" size="10" placeholder='Enter Email'></input>  
                  <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M20.822 18.096c-3.439-.794-6.64-1.49-5.09-4.418 4.72-8.912 1.251-13.678-3.732-13.678-5.082 0-8.464 4.949-3.732 13.678 1.597 2.945-1.725 3.641-5.09 4.418-3.073.71-3.188 2.236-3.178 4.904l.004 1h23.99l.004-.969c.012-2.688-.092-4.222-3.176-4.935z"/></svg>
                  </div>
                </div>
                <section>
                  <Calendar onChange={onChange} value={value} />
                </section>
              </div>

              <div>
                <button> Create </button>
              </div>
            </section>
          </section>
        </Template>
      </main>
    </div>
    )
  }



