import React from 'react'
import Head from 'next/head'
import Template from '../components/template/Template'

export default function CreateGoals() {

    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Template>
        </Template>
      </main>
    </div>
    )
  }
  