import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Template from '../components/template/Template'
import Loader from '../components/loader/Loader'
import HomeComp from '../components/home/Home'
import { useEffect } from 'react'
import Missions from '../components/missions/Missions'

export default function Home() {

  useEffect(() => {
    document.getElementById("loader").style.top = "-100%";
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Loader></Loader>
        <Template>
          <Missions/>
        </Template>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}


