import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function home() {
  return (
    <div>
      <head>
        <title> Login </title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main>
      </main>
    </div>
  )
}


