import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function home() {

  return (
    <div>
      <head>
        <title> Sign Up</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <main>
      </main>

      {/* <footer classname={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          powered by{' '}
          <span classname={styles.logo}>
            <image src="/vercel.svg" alt="vercel logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
